Some Additional Stuffs
Dude-Perfect-Discord-Bot/Dude-Perfect pull request #102
Opened 2021-05-11 15:22 UTC by deadshotofficial

This PR is same as the previous one just that I will do it bit-by-bit starting off with Utilities Section

2021-05-12 09:12 UTC, officialpiyush requested changes
I think it would be better if we check if the bot has `EMBED_LINKS` permission in the channels

2021-05-12 09:21 UTC, XynoxTheDev commented
> I think it would be better if we check if the bot has `EMBED_LINKS` permission in the channels

Yes, you are right @officialpiyush but @deadshotofficial is there really a need to have embedded for such commands providing very little information?

2021-05-13 11:46 UTC, deadshotofficial commented
@XynoxTheDev it is for adding to looks of commands, making it more attracting. and yeah about the PR Template, i just learned about it. for the next commands, i will check that too

2021-05-13 13:59 UTC, XynoxTheDev commented
> @XynoxTheDev it is for adding to looks of commands, making it more attracting. and yeah about the PR Template, i just learned about it. for the next commands, i will check that too

I think these commands are fine and are simple to be used without any permission checks. You can contribute by adding new features and upgrading other commands which are used very often not as utility commands.

2021-05-13 17:22 UTC, Anish-Shobith commented
well its quite easy @deadshotofficial ,
```js
const { Command } = require('discord-akario');

class ExampleCommand extends Command {

	constructor() {
		super('example', {
			clientPermission: 'EMBED_LINKS'
		})
	}
}
```

2021-05-13 17:24 UTC, Anish-Shobith commented on src/commands/Utilities/invite.js
> +        .setFooter(`${this.client.user.username} is made with ❤️`, `https://cdn.discordapp.com/emojis/805614116937007165.png?v=1`)
semi colon at the end please

2021-05-13 17:25 UTC, Anish-Shobith requested changes

2021-05-13 17:25 UTC, Anish-Shobith commented on src/commands/Utilities/invite.js
> +        message.channel.send(embed)
semi colon at the end please.

2021-05-13 17:25 UTC, Anish-Shobith commented on src/commands/Utilities/support.js
> +        .setFooter(`${this.client.user.username} is made with ❤️`, `https://cdn.discordapp.com/emojis/805614116937007165.png?v=1`)
semi colon at the end please.

2021-05-13 17:25 UTC, Anish-Shobith commented on src/commands/Utilities/support.js
> +        message.channel.send(embed)
semi colon at the end please.

2021-05-13 17:35 UTC, XynoxTheDev commented
Well, these changes are alright but I would make this PR a draft and it can be implemented in the future will further modification.

2021-05-13 17:37 UTC, XynoxTheDev reviewed
Well, these changes are alright but I would make this PR a draft and it can be implemented in the future will further modification.

2021-05-17 05:33 UTC, Anish-Shobith commented
@deadshotofficial any progress on this ?

2021-06-29 03:17 UTC, closed without merging

2021-06-29 03:18 UTC, XynoxTheDev commented
This PR is inactive for so long and no response from the contributor is there till now, so I'm closing this issue.