fix(voiceKick): response error
Dude-Perfect-Discord-Bot/Dude-Perfect pull request #129
Opened 2021-06-29 03:08 UTC by XynoxTheDev

## Details

- **Name:** fix(voiceKick): response error.
(Prefer to use [Github Commits](https://www.conventionalcommits.org/en/v1.0.0/))
- **Referencing Issue:** closes #124 
- **Description:** Fix that if the user is not connected to a voice channel then the bot will check that and reply with an error message.
- **Code Review:** @officialpiyush & @Anish-Shobith 

## Checklist

- [x] Have you followed the [contributing guidelines](https://github.com/Dude-Perfect-Discord-Bot/Dude-Perfect/blob/main/.github/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

> **Note**: We will close your PR without comment if you do not check the boxes above and provide ALL requested information.

2021-06-29 03:13 UTC, Anish-Shobith approved these changes

2021-06-29 03:13 UTC, officialpiyush requested changes

2021-06-29 03:13 UTC, officialpiyush commented on src/index.js
> +        '365644930556755969',
I already have my ID in there, this is an extra

2021-06-30 03:28 UTC, officialpiyush requested changes

2021-06-30 03:28 UTC, officialpiyush commented on src/index.js
> +        '365644930556755969',
I already have my ID n the array pt 2. check the last element of the array

2021-07-05 09:32 UTC, officialpiyush approved these changes

2021-07-05 12:07 UTC, closed without merging

2021-07-05 12:08 UTC, Anish-Shobith commented
wtf